### ISSUE TITLE
Why there are many hard-coded symbol links in cadence_libs

### ISSUE THREAD

**Issue by zhliang-work** [ucb-art/bag3_ams_cds_ff_mpt#2]
Hi, I am wondering why there are so many hard-coded symbol links in that folder.
It looks like all of these links are linked to some dynamic shared libraries.
Why not use something like `LDFLAGS `?

**Comment by ayan-biswas** [comment]
Thanks for raising this issue. It has been resolved. Please follow the instructions in the updated README.
