### ISSUE TITLE
while compile cbag, keep saying can not find "oaDesignDB.h"

### ISSUE THREAD

**Issue by extraord** [ucb-art/bag3_ams_cds_ff_mpt#3]
bag3++ claim full open sourced, but it looks like this header file is close sourced.

**Comment by ayan-biswas** [comment]
Please double-check your submodule commits, particularly for BAG_framework/pybag. It sounds like you are on an incorrect commit, and instead need to switch to the commit which removes the dependency on that header file. Following the steps in the README should put you on the correct commits for the submodules.

**Comment by extraord** [comment]
but I've checked back and forth, during the compiling (I use the command in README), it keep saying  "pybag/cbag/include/cbag/oa/database.h:55:10 : fatal error: oa/oaDesignDB.h' no such file or directory.

**Comment by ayan-biswas** [comment]
Can you please check 2 things?
1. During the compilation step, do you see the statement "Building without OpenAccess support"? If not, you are somehow on an incorrect commit in pybag, and we can try diving deeper into why this happened. If yes, move to the next point.
2. In .bashrc, when you updated the CDS_INST_DIR in line 23, did you verify that the OA_CDS_ROOT in line 33 exists? That oa version number may be different depending on your IC or ICADV version, so you have to put the correct directory name there.

**Comment by extraord** [comment]
finally, it turns out the version mismatch of enviorment packages make the issue. after sync with the official one, it works.
